### ISSUE TITLE
Feature testing

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/tsuserver3#78]
It seems that too many features have been added to tsuserver3 (mine included) without adequate testing. There are various features that have regressed according to server owners, but server owners cannot provide a full list of issues to report. I'm not going to wait on them to report everything.

The problem is that tsuserver isn't unit tested and isn't adequately set up for unit tests either. For now, it'll have to be a manual test. The whole point of this excursion is to hunt for bugs.

Now, there are some obvious items that I don't want to bore you with, so I'll only list feature that seem to be problematic or haven't been tested in an eternity.

### Server start

- [ ] Pip is correctly detected even when not on the PATH
- [ ] All requirements are installed correctly
- [x] When a config error occurs, the server pauses to show the error (#80)
  - [x] `config.yaml`
  - [x] `music.yaml`
  - [x] `characters.yaml`
  - [x] `areas.yaml`
  - [x] `backgrounds.yaml`
  - [x] Character INI files

### Core

- Strict mode (disables ini swapping by enforcing `char.ini` files)
  - [x] Can send the last emote over IC (related to a regression)
  - [x] Does not panic on case-sensitivity errors
  - [x] Does not panic on missing or bad `SoundN`/`SoundT` values
  - [x] Does not fail loading due to a single parsing error
  - [x] Prints an intelligible parsing error message
- Evidence
  - [ ] Can create evidence
  - [ ] Evidence limit is properly hit
  - [ ] When deleting evidence, evidence can still be added (evidence counter is properly incremented/decremented)
  - [ ] Can't edit evidence that has already been deleted (one client tries to edit evidence that was deleted)
- [x] Zalgo text is stripped (#81)

### webAO

- [x] Can make webAO connection
- [x] webAO connection is not lost after `timeout` setting in config
- [x] Client is dropped from the client list after unexpected disconnect

### Sockets

- [ ] Multi-client counter remains in sync with actual count of clients with same IPID

### Master server

- [x] Can make master server connection
- [x] Server appears on server list
- [x] Server appears on webAO list
- [ ] After server starts and is advertising, disconnect from the Internet and reconnect so that the advertiser starts up again. When server stops, the server should no longer appear on the list (related to various regressions with the MS advertiser)

#### Admin

- [x] /motd
  - /help
  - [x] `/help`
  - [x] `/help <command>`
- /kick
  - [ ] `/kick <ipid> <reason>`
  - [ ] `/kick * <reason>`
  - [ ] `/kick ** <reason>`
  - Reason should appear in all kicks
- /ban
  - [ ] `/ban <ipid> <reason>`
  - [ ] `/ban <ipid> <banid>`
  - Ban on existing IPID should return an error
  - Ban should kick the player
- /banhdid
  - [ ] `/banhdid <ipid> <reason>`
  - [ ] `/banhdid <ipid> <banid>`
  - A ban on an existing IPID but new HDID should add the HDID to the existing ban (even if ban id was never explicitly specified)
- [ ] /unban
- [ ] /mute
- [ ] /unmute
- [x] /login
- [x] /refresh
  - [ ] Refreshing should revoke credentials on a user if their profile was removed from the modpass config
- [x] /online
- [x] /mods (#84)
- [x] /unmod
- [x] /ooc_mute
- [ ] /ooc_unmute
- [ ] /bans
  - Should return in the correct order
- [ ] /baninfo
  - Should return the correct "banned by" name

#### Areas/rooms

- [x] /bg
- [x] /bglock
- [x] /allow_iniswap
- [x] /allow_blankposting
- [x] /force_nonint_pres
- /status
  - [x] `/status`
  - [x] `/status <status>`
  - [x] `/status <invalid-value>`
    - Should not trigger server error
- [x] /area
- [x] /getarea
- [x] /getareas
- [ ] /area_lock
- [ ] /area_spectate
- [ ] /area_unlock
- ~~/invite~~ (this feature has various issues, like referencing users by character ID rather than IPID)
- ~~/uninvite~~
- /area_kick
  - [ ] `/area_kick afk <room>`
  - [ ] `/area_kick <cid> <room>`
  - [ ] `/area_kick <cid> <nonexistent-room>`
- /getafk
  - [x] `/getafk`
  - [x] `/getafk all`
  - [ ] Should not show disconnected players (issue #85)

#### Casing

- [x] /doc
- [x] /cleardoc
- ~~/evidence_mod~~ (this feature is not well-understood and should be considered for removal or serious modification)
- [ ] /evi_swap
- [ ] /cm
- [ ] /uncm
- [ ] /setcase
- [ ] /anncase
- [ ] /blockwtce
- [ ] /unblockwtce
- [ ] /judgelog (#86)
- [x] /afk

#### Character

- [x] /switch
- [x] /pos
- [x] /forcepos
- [x] /charselect
- [x] /randomchar
- [ ] /charcurse
- [ ] /uncharcurse
- [ ] /charids
- [x] /reload

#### Fun

- [ ] /disemvowel
- [ ] /undisemvowel
- [ ] /shake
- [ ] /unshake

#### Messaging

- [x] /a
- [x] /s
- [x] /g
- [x] /gm
- [x] /m
- [x] /lm
- [x] /announce
- [ ] /toggleglobal
- [x] /need
- [ ] /toggleadverts
- [ ] /pm
- [ ] /mutepm

#### Music

(May be difficult to test due to the need for multiple users.)

- [ ] /currentmusic
- [ ] /jukebox_toggle
- [ ] /jukebox_skip
- [ ] /jukebox
- [ ] /play
- [ ] /blockdj
- [ ] /unblockdj

#### Roleplay

- [x] roll
- [x] rollp
- [x] notecard
- [x] notecard_clear
- [x] notecard_reveal
- [x] rolla_reload
- [x] rolla_set
- [x] rolla
- [x] coinflip
- [x] 8ball
